### ISSUE TITLE
Initial code structure stuff

### ISSUE THREAD

**Issue by maxscheurer** [maxscheurer/taco#2]
# General
- `qcelemental` for molecule representation

# ToDo
- [x] driver routines (`make_taco(mol1, mol2, "hf-in-hf", backend="psi4")`), molecule input
- [x] "wrapper" for host-program-specific routines (integrals)
    - [x] run SCF ground-state
    - [x] run embedded SCF with extra potential
    - [x] get integrals, operators, etc.
    - [x] tests
